// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Request
	Response
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Type int32

const (
	Response_NIL        Response_Type = 0
	Response_OK         Response_Type = 1
	Response_RAW_STRING Response_Type = 2
	Response_STRING     Response_Type = 3
	Response_INT        Response_Type = 4
	Response_SLICE      Response_Type = 5
	Response_ERR        Response_Type = 6
)

var Response_Type_name = map[int32]string{
	0: "NIL",
	1: "OK",
	2: "RAW_STRING",
	3: "STRING",
	4: "INT",
	5: "SLICE",
	6: "ERR",
}
var Response_Type_value = map[string]int32{
	"NIL":        0,
	"OK":         1,
	"RAW_STRING": 2,
	"STRING":     3,
	"INT":        4,
	"SLICE":      5,
	"ERR":        6,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Request is a request to a server.
type Request struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// Response is a response that contains command's execution result.
type Response struct {
	Result *Response_Result `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() *Response_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Response_Result struct {
	Type  Response_Type `protobuf:"varint,1,opt,name=type,enum=Response_Type" json:"type,omitempty"`
	Item  string        `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	Items []string      `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *Response_Result) Reset()                    { *m = Response_Result{} }
func (m *Response_Result) String() string            { return proto.CompactTextString(m) }
func (*Response_Result) ProtoMessage()               {}
func (*Response_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Result) GetType() Response_Type {
	if m != nil {
		return m.Type
	}
	return Response_NIL
}

func (m *Response_Result) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Response_Result) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_Result)(nil), "Response.Result")
	proto.RegisterEnum("Response_Type", Response_Type_name, Response_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Godown service

type GodownClient interface {
	ExecuteCommand(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type godownClient struct {
	cc *grpc.ClientConn
}

func NewGodownClient(cc *grpc.ClientConn) GodownClient {
	return &godownClient{cc}
}

func (c *godownClient) ExecuteCommand(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Godown/ExecuteCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Godown service

type GodownServer interface {
	ExecuteCommand(context.Context, *Request) (*Response, error)
}

func RegisterGodownServer(s *grpc.Server, srv GodownServer) {
	s.RegisterService(&_Godown_serviceDesc, srv)
}

func _Godown_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GodownServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Godown/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GodownServer).ExecuteCommand(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Godown_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Godown",
	HandlerType: (*GodownServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _Godown_ExecuteCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0x7f, 0x9b, 0x66, 0x84, 0xb0, 0x0c, 0x1e, 0x42, 0x4f, 0x25, 0x22, 0xe4, 0x14, 0x21,
	0x3e, 0x81, 0x94, 0x50, 0x82, 0x25, 0xca, 0x34, 0xe8, 0x51, 0x6a, 0x3b, 0x87, 0x42, 0x93, 0x8d,
	0xcd, 0x06, 0xed, 0xcb, 0xfa, 0x2c, 0x92, 0x4d, 0xaa, 0xa7, 0xfd, 0x7e, 0xd9, 0xdd, 0x0f, 0x82,
	0x6d, 0x7b, 0x48, 0xdb, 0x93, 0xd2, 0x2a, 0xbe, 0x05, 0x9f, 0xf8, 0xb3, 0xe7, 0x4e, 0x63, 0x04,
	0xfe, 0x4e, 0xd5, 0xf5, 0xb6, 0xd9, 0x47, 0xd6, 0xc2, 0x4a, 0x02, 0xba, 0xd0, 0xf8, 0xc7, 0x82,
	0x19, 0x71, 0xd7, 0xaa, 0xa6, 0x63, 0x4c, 0x40, 0x9c, 0xb8, 0xeb, 0x8f, 0xda, 0xa4, 0xae, 0x33,
	0x99, 0x5e, 0xac, 0x01, 0xf4, 0x47, 0x4d, 0x93, 0x3f, 0x7f, 0x05, 0x31, 0x2a, 0x18, 0x83, 0xab,
	0xcf, 0x2d, 0x9b, 0x46, 0x98, 0x85, 0xff, 0x8d, 0xea, 0xdc, 0x32, 0x19, 0x0f, 0x11, 0xdc, 0x83,
	0xe6, 0x3a, 0xb2, 0xcd, 0xdd, 0x06, 0xe3, 0x0d, 0x78, 0xc3, 0xd9, 0x45, 0xce, 0xc2, 0x49, 0x02,
	0x1a, 0x49, 0xfc, 0x02, 0xee, 0xd0, 0x43, 0x1f, 0x9c, 0xb2, 0x58, 0xcb, 0x2b, 0x14, 0x60, 0x3f,
	0x3f, 0x49, 0x0b, 0x43, 0x00, 0x7a, 0x7c, 0x7b, 0xdf, 0x54, 0x54, 0x94, 0x2b, 0x69, 0x23, 0x80,
	0x98, 0xb0, 0x33, 0x84, 0x8b, 0xb2, 0x92, 0x2e, 0x06, 0xe0, 0x6d, 0xd6, 0xc5, 0x32, 0x97, 0xde,
	0xa0, 0xe5, 0x44, 0x52, 0x64, 0xf7, 0x20, 0x56, 0x6a, 0xaf, 0xbe, 0x1a, 0xbc, 0x83, 0x30, 0xff,
	0xe6, 0x5d, 0xaf, 0x79, 0x39, 0x7e, 0x1e, 0x67, 0xe9, 0x34, 0xd0, 0x3c, 0xf8, 0x7b, 0xf7, 0x87,
	0x30, 0xeb, 0x3d, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x47, 0x0f, 0x40, 0x6d, 0x4a, 0x01, 0x00,
	0x00,
}
